"""Initial migration with cipher_solved and next_cipher_time fields

Revision ID: 02edae24c5c1
Revises: 
Create Date: 2024-07-13 22:20:21.853906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02edae24c5c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_points')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cipher_solved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('next_cipher_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('next_cipher_time')
        batch_op.drop_column('cipher_solved')

    op.create_table('game_points',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('points', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
